(() => {
  const records = {
    patient: {title:'Patient', status:'Core record · intended model', description:'The persistent person and their clinician-relevant history in Heidi.', fields:'Heidi patient ID, identifying details, saved context, linked EHR identifiers when available.', relation:'One patient has zero or more encounters. A patient can exist before an encounter or session.', retention:'The profile and deliberately saved details can persist independently of session content. Exact duration, deletion and EHR-only patient retention remain open.', decision:'Does an explicit save, task or encounter retain an EHR-visible patient before the first session?'},
    encounter: {title:'Encounter', status:'Core record · lifecycle decisions open', description:'One period of care for one patient: an appointment or inpatient stay.', fields:'Heidi encounter ID, patient, care type, nature of care, start/end, location, status; optional EHR link.', relation:'One patient per encounter; zero or more sessions. Each appointment is separate. An inpatient period can span multiple rounds. The connector means membership after assignment.', retention:'Whether encounter metadata survives expired sessions, and for how long, is unresolved. Ending care is different from deleting its record.', decision:'Confirm provisional type, corrections, reopening, concurrent inpatient periods and stored versus effective encounters.'},
    session: {title:'Session', status:'Core record · unassigned capture supported', description:'A clinician-initiated captured touchpoint. Resuming continues the same session; a new touchpoint can create another session.', fields:'Session ID, capture times, clinician, capture/transcript content, patient and encounter context when assigned.', relation:'Can begin without patient or encounter. Once assigned, create/select an encounter. Multiple documents can come from one session; first-release document scope remains open.', retention:'Expiry of session content is the scenario shown here. Which content expires, its duration, and whether metadata remains require definition.', decision:'What happens to documents and source links after expiry? Do not infer a cascade from the arrows.'},
    context: {title:'Saved patient context', status:'Patient-owned information · not necessarily a separate table', description:'Details deliberately maintained for use across visits, such as patient history and concise clinician context.', fields:'Content, who maintained it and its source/update history where available. Provenance fields are proposed.', relation:'Belongs to the patient. Showing a session upload in patient history does not automatically convert it into persistent patient context.', retention:'Intended to persist independently of session content. Retention period and explicit patient deletion rules remain open.', decision:'Define the action that saves session information as patient context, and distinguish it from EHR-supplied information.'},
    task: {title:'Task', status:'Core record · exact context rules open', description:'A lightweight action with an owner and status. General tasks need no patient, encounter or source session.', fields:'Task ID, title, details, owner, status and optional source/context links.', relation:'May link to an encounter and source session. A session-derived task follows encounter assignment. Patient-only task links and later reassignment rules remain decisions.', retention:'Task lifetime, completion history and source-link behaviour after session expiry are unresolved. Completion does not establish a deletion date.', decision:'Allow patient-level tasks? What survives a deleted source? Accepting a suggestion and asking Heidi to execute are separate actions.'},
    document: {title:'Document', status:'Output · ownership still to confirm', description:'A note, letter or instructions. A session note retains its source session; broader encounter outputs are later scope.', fields:'Document identity, content, source, revision and review state. Exact schema and first-release capabilities remain open.', relation:'The diagram shows session-derived documents. Proposed: session notes are owned by sessions; broader outputs by encounters; patient history surfaces both.', retention:'Whether the document expires with its source or can be retained independently is undecided. There is no implied automatic copy or permanent retention.', decision:'Can documents exist directly under a patient? Confirm ownership, multi-session sources and retention separately.'},
    delivery: {title:'Delivery history', status:'Per-document delivery accepted · receipt model proposed', description:'Tracks whether a particular note was shared or pushed, separately from whether the session ended.', fields:'Proposed: document revision, channel, destination, attempted time, outcome and receipt.', relation:'A document can have multiple delivery attempts. Editing after delivery leaves changes not yet sent. EHR linkage alone is not evidence of successful delivery.', retention:'Receipt retention and the behaviour of copies outside Heidi need definition. Deleting Heidi content must not imply an external copy was deleted.', decision:'What confirms shared/exported/pushed? Which channels support reliable receipts? Prototype statuses are examples, not live integrations.'},
    routine: {title:'Routine and runs', status:'Proposed model · later capability', description:'Separate recurring instructions from each execution so one routine can produce many runs over time.', fields:'Proposed: routine instructions and schedule; run ID, timing, outcome and linked tasks/outputs.', relation:'Dotted link illustrates a possible run creating or updating work. A routine can also produce general outputs without patient context.', retention:'Instructions, execution history and generated outputs may need different policies. No durations or cascade rules are agreed.', decision:'Define ownership, supported execution and output retention when routines enter scope. Current examples do not execute.'},
    ehrPatient: {title:'EHR patient link', status:'Optional integration relationship', description:'An external patient record remains identified by its source system and EHR patient ID.', fields:'External system/organisation, external patient ID, Heidi patient link and link status. Matching metadata is proposed.', relation:'EHR details and Heidi-maintained information must remain distinguishable. The EHR remains the system of record for its clinical record.', retention:'The PRD ties retention of inactive EHR-visible patients to session creation, but explicitly leaves saves, tasks and encounters before a session unresolved.', decision:'Define matching, duplicate handling, editable fields, sync conflicts and when a Heidi profile is retained.'},
    ehrEncounter: {title:'EHR encounter link', status:'Optional integration relationship', description:'A separate external encounter reference linked to the Heidi period of care when reliably identified.', fields:'Source system, external encounter ID and link status; Heidi encounter ID remains distinct.', relation:'A linked patient does not automatically link every encounter. Later matching of a Heidi-created encounter is desired but not yet defined.', retention:'EHR availability, Heidi retention and note delivery are separate concerns. No bidirectional deletion or write permission is implied.', decision:'Define late matching, duplicates, ended encounters, access and integration-specific writeback rules.'}
  };
  let selected='patient';
  const detail=document.getElementById('record-detail');
  const showDetail=()=>{ const r=records[selected]; detail.innerHTML=`<h2 id="detail-title">${r.title}</h2><p class="detail-status">${r.status}</p><p>${r.description}</p><h3>Identity and information</h3><p>${r.fields}</p><h3>Relationships</h3><p>${r.relation}</p><h3>Retention</h3><p>${r.retention}</p><h3>Still to decide</h3><p>${r.decision}</p>`; document.querySelectorAll('[data-node]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.node===selected))); };
  const edges=[['patient','encounter','0…many','solid'],['encounter','session','0…many','solid'],['patient','context','maintains','solid'],['encounter','task','optional context','dashed'],['task','session','source session','dashed'],['session','document','0…many','solid'],['document','delivery','0…many attempts','solid'],['routine','task','may create work','proposed']];
  function draw(){
    const svg=document.getElementById('connectors'), map=document.querySelector('.model-map'), box=map.getBoundingClientRect(), narrow=window.innerWidth<=650;
    const all=document.body.classList.contains('ehr-mode')?[['ehr-patient','patient','optional match','dashed'],['ehr-encounter','encounter','optional match','dashed'],...edges]:edges;
    svg.setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);
    let markup='<defs><marker id="model-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path class="arrow-tip" d="M0 0 L7 3.5 L0 7 Z"/></marker></defs>';
    all.forEach(([a,b,label,style],index)=>{
      const ar=document.getElementById(a).getBoundingClientRect(),br=document.getElementById(b).getBoundingClientRect();
      let d,x,y,anchor='middle';
      if(narrow){
        const ay=ar.top-box.top+ar.height/2, by=br.top-box.top+br.height/2, ax=ar.left-box.left,bx=br.left-box.left,lane=4+(index%3)*7;
        d=`M${ax} ${ay} H${lane} V${by} H${bx-3}`; x=bx+8;y=br.top-box.top-18; anchor='start';
      } else if(Math.abs(ar.top-br.top)<10){ const x1=ar.right-box.left,x2=br.left-box.left,y1=ar.top-box.top+ar.height/2; d=`M${x1} ${y1} H${x2-4}`;x=(x1+x2)/2;y=y1-10; }
      else if(a==='task' && b==='session'){ const x1=ar.right-box.left,x2=br.left-box.left,y1=ar.top-box.top+ar.height/2,y2=br.top-box.top+br.height/2,mid=(x1+x2)/2;d=`M${x1} ${y1} H${mid} V${y2} H${x2-4}`;x=mid;y=(ar.top+br.bottom)/2-box.top+16; }
      else { const down=br.top>ar.top, x1=ar.left-box.left+ar.width/2,x2=br.left-box.left+br.width/2,y1=(down?ar.bottom:ar.top)-box.top,y2=(down?br.top:br.bottom)-box.top,mid=(y1+y2)/2;d=`M${x1} ${y1} V${mid} H${x2} V${y2+(down?-4:4)}`;x=(x1+x2)/2;y=mid-9; }
      markup+=`<path d="${d}" ${style==='solid'?'':`stroke-dasharray="${style==='dashed'?'5 5':'2 5'}"`} marker-end="url(#model-arrow)"/><text x="${x}" y="${y}" text-anchor="${anchor}">${label}</text>`;
    });
    svg.innerHTML=markup;
    document.getElementById('map-relationships').innerHTML=all.map(([a,b,label])=>`<li>${document.getElementById(a).querySelector('strong').textContent} → ${document.getElementById(b).querySelector('strong').textContent}: ${label}</li>`).join('');
  }
  document.querySelectorAll('[data-node]').forEach(n=>n.addEventListener('click',()=>{selected=n.dataset.node;showDetail(); if(window.innerWidth<=1150) document.querySelector('.model-detail').scrollIntoView({block:'nearest',behavior:'instant'});}));
  document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{
    const ehr=button.dataset.mode==='ehr';document.body.classList.toggle('ehr-mode',ehr);
    document.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n===button)));
    document.querySelectorAll('.external').forEach(n=>n.hidden=!ehr);
    document.getElementById('mode-description').textContent=ehr?'EHR-connected · The same Heidi model gains external patient and encounter links. Imported information, permissions and note delivery remain separate.':'Heidi-only · The clinician creates patients and encounters. Capture can start before either is assigned.';
    document.getElementById('delivery-channel').textContent=ehr?'EHR push / share where supported':'Share / export where supported';
    if(!ehr && selected.startsWith('ehr')){selected='patient';showDetail();} draw();
  }));
  document.getElementById('retention').addEventListener('change',event=>{
    const enabled=event.target.checked; document.body.classList.toggle('expiry-mode',enabled);document.getElementById('expiry-note').hidden=!enabled;
    document.querySelectorAll('[data-expiry]').forEach(n=>n.textContent=enabled?n.dataset.expiry:n.dataset.normal);draw();
  });
  showDetail();new ResizeObserver(draw).observe(document.getElementById('map-grid'));document.fonts.ready.then(draw);window.addEventListener('resize',draw);
})();
